### ISSUE TITLE
Common DB interface?

### ISSUE THREAD

**Issue by didip** [hsluoyz/casbin#3]
Hi, first of all, awesome project. This kind of things are always needed for UI-like app.

Would you consider writing a common interface so that a different database can be used? for example Cassandra (via gocql)?

**Comment by hsluoyz** [comment]
Thanks for this issue!

Currently casbin adopts an adapter model for policy persistence. It already supports file, RDBMS, but not NoSQL yet.

After googling around NoSQL, I found Cassandra, MongoDB, HBase, etc. They have different clients in Go, so they can't be supported by the same code. Which NoSQL DB do you think is better or are you using? Of course, if there's a general client for all NoSQL DBs, it would be best.

**Comment by didip** [comment]
I am currently at an all 100% Cassandra shop :)

I think you can support multiple databases by structuring them under separate directory (package).

In each package you can then expose the DB handler factory by using `init()` so that user can pick and choose which one to load during runtime.

With a common interface, you can just pick a few of the most popular ones and let contributors add their favorite databases themselves.

Just my 2 cents.

**Comment by hsluoyz** [comment]
Hi. I have downloaded the tar ball of Cassandra and run ``bin/cassandra -f -R`` in my Ubuntu. But I failed to connect to it via DBeaver (a GUI client that supports Cassandra DB) as the below picture. 

I don't know what is the keyspace, and the default user password?

![image](https://cloud.githubusercontent.com/assets/3787410/25310804/36cd408a-2820-11e7-9d19-4e90f3641705.png)

**Comment by didip** [comment]
default installation should provide an admin user called cassandra/cassandra for username and password.

From there, you can create a new keyspace.

**Comment by hsluoyz** [comment]
Hi.

Cassandra support has been added to casbin since 0.0.5. It uses a plugin design to keep the main code light-weight.

Please see details at: https://github.com/hsluoyz/casbin#persistence

**Comment by hsluoyz** [comment]
I will close it for now since it has been solved.
