### ISSUE TITLE
authorization middleware for chi framework

### ISSUE THREAD

**Issue by msaron** [hsluoyz/casbin#5]
Could you create an authorization middleware for the [chi](https://github.com/pressly/chi) framework? It would be most helpful. Read about this library through the Go Newsletter from [Golang Weekly](https://golangweekly.com/)

Thanks.

**Comment by hsluoyz** [comment]
I have asked chi's permission to create the middleware: https://github.com/pressly/chi/issues/191. The process is on going now:)

**Comment by hsluoyz** [comment]
PR is submitted here: https://github.com/pressly/chi/pull/192

**Comment by hsluoyz** [comment]
The casbin middleware has been added here: https://github.com/pressly/chi#middlewares
